"$schema" = 'https://starship.rs/config-schema.json'

format = """
[ÓÇ∂](color_bg3)\
$os\
$username\
[ÓÇ∞](bg:color_purple fg:color_bg3)\
$directory\
[ÓÇ∞](fg:color_purple bg:color_yellow)\
$git_branch\
$git_status\
[ÓÇ∞](fg:color_yellow bg:color_orange)\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[ÓÇ∞](fg:color_orange bg:color_dkblue)\
$docker_context\
$conda\
$pixi\
[ÓÇ∞](fg:color_dkblue bg:color_bg3)\
$time\
[ÓÇ¥ ](fg:color_bg3)\
$line_break$character"""

palette = 'dracula'

# Define Dracula color palette
[palettes.dracula]
color_bg1 = "#282a36"
color_bg3 = "#44475a"
color_fg0 = "#0b0107"
color_dkblue = "#6272a4"
color_blue = "#3f93ec"
color_aqua = "#8be9fd"
color_green = "#50fa7b"
color_orange = "#ffb86c"
color_pink = "#ff79c6"
color_purple = "#bd93f9"
color_red = "#ff5555"
color_yellow = "#f1fa8c"

[os]
disabled = false
style = "bg:color_bg3 fg:color_purple"

[os.symbols]
Windows = "Û∞ç≤"
Ubuntu = "Û∞ïà"
SUSE = "Ôåî"
Raspbian = "Û∞êø"
Mint = "Û∞£≠"
Macos = "Û∞Äµ"
Manjaro = "Ôåí"
Linux = "Û∞åΩ"
Gentoo = "Û∞£®"
Fedora = "Û∞£õ"
Alpine = "ÔåÄ"
Amazon = "Ôâ∞"
Android = "Óúé"
AOSC = "ÔåÅ"
# Arch = "Û∞£á"
Arch = "Û∞£á"
Artix = "Û∞£á"
EndeavourOS = "ÔÜó"
CentOS = "ÔåÑ"
Debian = "Û∞£ö"
Redhat = "Û±Ñõ"
RedHatEnterprise = "Û±Ñõ"
Pop = "Ôå™"

[username]
show_always = true
style_user = "bg:color_bg3 fg:color_purple"
style_root = "bg:color_bg3 fg:color_purple"
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg0 bg:color_purple"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "‚Ä¶/"

[directory.substitutions]
"Documents" = "Û∞àô "
"Downloads" = "ÔÄô "
"Music" = "Û∞ùö "
"Pictures" = "ÔÄæ "
"Developer" = "Û∞≤ã "

[git_branch]
symbol = "Ôêò"
style = "bg:color_yellow"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_yellow)]($style)'

[git_status]
style = "bg:color_yellow"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_yellow)]($style)'

[nodejs]
symbol = "Óúò"
style = "bg:color_dkblue"
format = '[[ $symbol( $version) ](fg:color_dkblue bg:color_orange)]($style)'

[c]
symbol = "Óòû "
style = "bg:color_dkblue"
format = '[[ $symbol( $version) ](fg:color_dkblue bg:color_orange)]($style)'

[cpp]
symbol = "Óòù "
style = "bg:color_dkblue"
format = '[[ $symbol( $version) ](fg:color_dkblue bg:color_orange)]($style)'

[rust]
symbol = "Óû®"
style = "bg:color_dkblue"
format = '[[ $symbol( $version) ](fg:color_dkblue bg:color_orange)]($style)'

[golang]
symbol = "Óòß"
style = "bg:color_dkblue"
format = '[[ $symbol( $version) ](fg:color_dkblue bg:color_orange)]($style)'

[php]
symbol = "Óòà"
style = "bg:color_dkblue"
format = '[[ $symbol( $version) ](fg:color_dkblue bg:color_orange)]($style)'

[java]
symbol = "Óâñ"
style = "bg:color_dkblue"
format = '[[ $symbol( $version) ](fg:color_dkblue bg:color_orange)]($style)'

[kotlin]
symbol = "Óò¥"
style = "bg:color_dkblue"
format = '[[ $symbol( $version) ](fg:color_dkblue bg:color_orange)]($style)'

[haskell]
symbol = "Óòü"
style = "bg:color_orange"
format = '[[ $symbol( $version) ](fg:color_dkblue bg:color_orange)]($style)'

[python]
symbol = "ÓòÜ"
style = "bg:color_orange"
format = '[[ $symbol( $version) ](fg:color_dkblue bg:color_orange)]($style)'

[docker_context]
symbol = "Ôåà"
style = "bg:color_dkblue"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[conda]
style = "bg:color_dkblue"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_bg3)]($style)'

[pixi]
style = "bg:color_dkblue"
format = '[[ $symbol( $version)( $environment) ](fg:color_fg0 bg:color_bg3)]($style)'

[time]
disabled = false
time_format = "%l:%M %p"
style = "bg:color_dkblue"
format = '[[ Ôê∫ $time ](fg:color_green bg:color_bg3)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[ü¶á ‚ùØ](bold fg:color_green)'
error_symbol = '[‚ö∞Ô∏è ‚úó](bold fg:color_red)'

